FROM php:7.4-fpm

RUN apt-get update && apt-get install -y -q curl wget unzip netcat \
        libzip-dev libmcrypt-dev libpq-dev libssl-dev libpcre3 libpcre3-dev zlib1g zlib1g-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install zip

## Cron installation and setup
RUN apt-get update && apt-get install -q -y cron rsyslog nano
ADD config/php/crontab.sh /etc/cron.d/crontab.sh
RUN chmod 0644 /etc/cron.d/crontab.sh
RUN crontab /etc/cron.d/crontab.sh
RUN touch /var/log/crontab.log && chmod 0644 /var/log/crontab.log

## Install pdo_mysql
RUN docker-php-ext-install mysqli pdo pdo_mysql

## Install Composer
RUN cd /bin && curl -sS https://getcomposer.org/installer | php && mv composer.phar composer
